### ISSUE TITLE
Reprezentácia miestnosti

### ISSUE THREAD

**Issue by maaario** [projektXP/hra#2]
Pôdorys je obdĺžnik.

2D pole objektov, zatiaľ globálna premenná, neskôr môže byť objektom.

Vieme ju načítať zo súboru (neskôr bude "súbor" generovaný).
Každý objekt má jeden znak na mape.

**Comment by michalpuskel** [comment]
1. kolo budem robit s Mr. Heinzom, neskor sa prestriedame
