### ISSUE TITLE
Príšery

### ISSUE THREAD

**Issue by maaario** [projektXP/hra#4]
Abstraktná classa Monster(?)
- metóda step, ktorá pohne príšeru (pred pohybom volá can_move(políčko) - +-globálna funkcia) / zmení jej stav - AI
- vlastné parametre: rýchlosť, following_me

Základné konkrétne príšery
- rýchla - naháňa ťa rýchlo odkedy ťa uvidí (odkedy ju uvidíš)
- pomalá - naháňa ťa od začiatku

**Comment by michalpuskel** [comment]
1. kolo budem robit s Mr. Heinzom, neskor sa prestriedame
